config/routes.rb
Rails.application.routes.draw do
  root "posts#top"
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  namespace :posts do
    resources :searches, only: :index
  end
  resources :posts do
    resources :comments, only: :create
    resources :likes, only: [:create, :destroy]
    member do
      get 'fromlike', 'forlike'
    end
  end
  resources :users, only: [:edit, :update, :show]
  put 'users/follow/:user_id' => 'users#follow'
  put 'users/unfollow/:user_id' => 'users#unfollow'

  get 'users/follow_list/:user_id' => 'users#follow_list'
  get 'users/follower_list/:user_id' => 'users#follower_list'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :text, presence: true
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" and "follower" interface
  belongs_to :followable, polymorphic: true
  belongs_to :follower,   polymorphic: true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :text, :image, presence: true
  belongs_to :user
  has_many :comments
  has_many :likes
  has_many :liked_users, through: :likes, source: :user
  mount_uploader :image, ImageUploader
  def self.search(search)
    if search
      Post.where('title LIKE(?)', "%#{search}%")
    else
      Post.all
    end
  end
  

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, uniqueness: true

  acts_as_followable
  acts_as_follower
  
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  # 上記のコードはログインしていないユーザーをログインページに飛ばすもので今はいらない。
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to post_path(comment.post.id)
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @like = current_user.likes.create(post_id: params[:post_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/posts/searches_controller.rb
class Posts::SearchesController < ApplicationController
  def index
    @posts = Post.search(params[:keyword]).order("created_at DESC").page(params[:page]).per(20)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # before_action :move_to_index,except: [:index]

  def index
    @posts = Post.includes(:user).order("created_at DESC").page(params[:page]).per(20)
  end

  def new
    @post = Post.new
  end

  def create
    Post.create(post_params)
    redirect_to root_path
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to post_path(post.id)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
    @like = Like.new
  end

  def fromlike
    @post = Post.find(params[:id])
  end

  def forlike
    user = User.find(params[:id])
    @user = user
    @posts = user.posts.page(params[:page]).per(20).order("created_at DESC")
  end

  # def gon
  #   gon.image = @post.image
  # end

  private
  def post_params
    params.require(:post).permit(:title, :text, :image).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def show
    user = User.find(params[:id])
    @user = user
    @name = user.name
    @posts = user.posts.page(params[:page]).per(20).order("created_at DESC")
  end

  def follow
    @user = User.find(params[:user_id])
    current_user.follow(@user)
    redirect_to user_path(@user)
  end

  def unfollow
    @user = User.find(params[:user_id])
    current_user.stop_following(@user)
    redirect_to user_path(@user)
  end

  def follow_list
    @user = User.find(params[:user_id])
  end

  def follower_list
    @user = User.find(params[:user_id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html(lang="ja")
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")/
    %title Sizeapp
    -# = include_gon
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/likes/_like.html.haml
-# -if current_user.already_liked?(@post)
-#   = link_to post_like_path(@post), class: "like-btn", method: :delete, remote: true do
-#     = icon('fas', 'heart', class: "like-icon-off")
-# -else
-#   = link_to post_likes_path(@post), class:"like-btn",method: :post, remote: true do
-#     = icon('fas', 'heart', class: "like-icon-on")
-# .like-count
-#   = link_to @post.likes.count, fromlike_post_path, class: "like-count-link"

app/views/posts/_footer.html.haml
%footer
  .footer__box
    .icons
      = link_to "https://twitter.com/", class: "twitter" do
        = icon('fab', 'twitter')
      = link_to "https://www.instagram.com/", class: "instagram" do
        = icon('fab', 'instagram')
      = link_to "https://www.facebook.com/", class: "facebook" do
        = icon('fab', 'facebook-square')
    .footer-logo
      JustMe &.
    .footer-text
      happy wear life
      -# <i class="fas fa-star-and-crescent"></i>
      -# 月のアイコン

app/views/posts/_header.html.haml
%header
  .header__box
    .header__logo
      %img(src="/assets/jasmin.png" alt="jasmin" width="70%" height="70%")/
    .header__text
      好きな服のサイズ感をみんなで共有するアプリ
      .appname
        = link_to root_path, class: "appname-link" do
          JustMe &.
    .user__icon
      -if user_signed_in?
        .user__icon--btn
          = link_to edit_user_path(current_user) do
            = image_tag current_user.image.url, width: '100%',height:'100%', class: "user__icon--circle"
    .user__box
      -if user_signed_in?
        .sign-btn
          -# = link_to edit_user_path(current_user), class: "login-btn-link" do
          = link_to user_path(current_user.id), class: "login-btn-link" do
            = current_user.name
        .login-btn
          = link_to destroy_user_session_path, method: :delete, class: "login-btn-link" do
            Log Out
      -else
        .sign-btn
          = link_to new_user_registration_path, class: "sign-btn-link" do
            Sign In
        .login-btn
          = link_to new_user_session_path, class: "login-btn-link" do
            Log In
      

app/views/posts/_search.html.haml
.search__bar
  .search__bar--text
    = form_with url: posts_searches_path, local: true, method: :get do |f|
      = f.text_field :keyword, class: "search-input", placeholder: "検索ワードを入力"
      = f.submit "検索", class: "search-btn"

%ul.content_search
  - @posts.each do |post|
    %li.search_post
      = link_to post_path(post.id), method: :get, class: "link__group" do
        .post_image
          = image_tag post.image.url, width: '100%',height:'100%'
          -# %img(src="post.image")
        %ul.post_title
          %li
            = truncate(post.title, length: 14, omission: "..")
          %li
            -# -if current_user.already_liked?(@post)
            = icon('fas', 'heart', class: "like-icon-off")
            -# -else
            -# = icon('fas', 'heart', class: "like-icon-on")
            = post.liked_users.count
= paginate(@posts)

app/views/posts/edit.html.haml
.wrapper
  = render "header"
  %content
    .content__box
      .content__details
        = form_with model: @post do |f|
          %h3
            編集ページ
          = f.text_area :title, value: @post.title, id: "title", autofocus: true
          = f.text_area :text, value: @post.text, id: "text"
          .default_image
            現在の画像
            = image_tag @post.image.url, width: '90%'
          = f.file_field :image, class: "dropify"
          = f.submit "SEND", id: "send-btn"
  = render "footer"

app/views/posts/forlike.html.haml
.wrapper
  = render "/posts/header"
  
  .show__user__page
    .show__user__details
      .show__user__details-icon
        = image_tag @user.image.url, width: '100%',height:'100%', class: "details-icon"
      .show__user__details-name
        = @user.name
        さんがいいねした投稿

      .show__user__details-like
  %ul.content_search
    - @user.liked_posts.each do |post|
      %li.search_post
        = link_to post_path(post.id), method: :get, class: "link__group" do
          .post_image
            = image_tag post.image.url, width: '100%',height:'100%'
            -# %img(src="post.image")
          %ul.post_title
            %li
              = post.title
            %li
              -# -if current_user.already_liked?(@post)
              = icon('fas', 'heart', class: "like-icon-off")
              -# -else
              -# = icon('fas', 'heart', class: "like-icon-on")
              = post.liked_users.count
    = paginate(@posts)
  = render "/posts/footer"

app/views/posts/fromlike.html.haml
.wrapper
  = render "header"
  .from
    .from__like
      この投稿にいいねした人
      -@post.liked_users.each do |user|
        %ul.from__like__user
          %li.from__like__icon
            = image_tag user.image.url, width: '100%',height:'100%', class: "from__icon__link"
          %li.from__like__name
            = link_to user.name, user_path(@post.user), class: "from__name__link"             

  = render "footer"

app/views/posts/index.html.haml
.wrapper
  = render "header"
  = render "main"
  = render "footer"

app/views/posts/new.html.haml
.wrapper
  = render "header"
  %content
    .content__box
      .content__details
        = form_with model: @post do |f|
          %h3
            投稿ページ
          = f.text_area :title, placeholder: "タイトルを入力", id: "title", autofocus: true
          = f.text_area :text, placeholder: "コメントを入力", id: "text"
          = f.file_field :image, class: "dropify"
          = f.submit "SEND", id: "send-btn"
  = render "footer"

app/views/posts/searches/index.html.haml
.wrapper
  = render "/posts/header"
  = render "/posts/search"
  = render "/posts/footer"

app/views/posts/show.html.haml
.wrapper
  = render "header"
  .show
    .show_box
      .show_details
        .show_title
          = @post.title
        .show_text
          = simple_format(@post.text)
        .show_user
          %ul.show_user_btns
            %li.show_user_icon
              = image_tag @post.user.image.url, width: '100%',height:'100%', class: "show__user--circle"
            %li.show_user_name
              = link_to @post.user.name, user_path(@post.user), class: "show-user-link"
            -# = render "likes/like"
            -if current_user.already_liked?(@post)
              = button_to post_like_path(@post), class: "like-btn", method: :delete do
                = icon('fas', 'heart', class: "like-icon-off")
            -else
              = button_to post_likes_path(@post), class:"like-btn" do
                = icon('fas', 'heart', class: "like-icon-on")
            .like-count
              = link_to @post.likes.count, fromlike_post_path, class: "like-count-link"
            -if user_signed_in? && current_user.id == @post.user_id
              %li.show_edit_btn
                = link_to edit_post_path(@post.id), class: "show_edit-link" do
                  = icon('fas', 'edit', class: "show__edit--icon")
              %li.show_delete_btn
                = link_to post_path(@post.id), method: :delete, class: "show_delete-link", data: {confirm: "本当に削除しますか？"} do
                  = icon('fas', 'trash-alt', class: "show__delete--icon")
        .show_comment
          = form_with model: [@post, @comment], local: true do |f|
            = f.text_area :text, placeholder: "コメントする", rows: "2", class: "comment_text_input"
            = f.submit "SEND", class: "comment_submit-btn"
          .show_comments
            コメント一覧
            -if @comments
              -@comments.each do |comment|
                .show_comments_box
                  = link_to comment.user.name, "/users/#{comment.user_id}", class: "comment_user-link"
                  .comment_text_show
                    = comment.text
            -# -elsif @comments == nil
            -# コメントはまだありません
            -# コメントがない時にコメントはないと入れたいがエラーが出て表示されない
      .show-image
        = image_tag @post.image.url, width: '80%'
  = render "footer"

app/views/posts/top.html.haml
.wrapper
  = render "header"
  %main
    .main__box
      .image__box
        .image__box--left
        .image__box--right
      .btn-box
        -if user_signed_in?
          .share__box
            = link_to new_post_path, class: "share__box--btn" do
              = icon('far', 'share-square', class: "share__box--icon")
              SHARE !
            .share__box--text
              持っている服のサイズ感をみんなに教えてあげよう
          .search__box
            = link_to posts_path, class: "search__box--btn" do
              = icon('fas', 'search', class: "search__box--icon")
              SEARCH !
            .search__box--text
              サイズ感が気になる服の情報をみんなに教えてもらおう
        -else
          .share__box
            = link_to new_user_session_path, class: "share__box--btn" do
              = icon('far', 'share-square', class: "share__box--icon")
              SHARE !
            .share__box--text
              持っている服のサイズ感をみんなに教えてあげよう
          .search__box
            = link_to new_user_session_path, class: "search__box--btn" do
              = icon('fas', 'search', class: "search__box--icon")
              SEARCH !
            .search__box--text
              サイズ感が気になる服の情報をみんなに教えてもらおう
  = render "footer"

app/views/users/_follow_form.html.haml
.follow_form
  - if current_user.following? @user
    = link_to "フォローを外す", {controller: :users,action: :unfollow,user_id: @user.id}, class: "unfollow__btn", method: :put
  - else
    = link_to "フォローする", {controller: :users,action: :follow,user_id: @user.id}, class: "follow__btn", method: :put

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", root_path, class: 'btn'
      .edit__icon
        現在のアイコン
        = image_tag current_user.image.url, width: '100%',height:'100%', class: "edit__user--circle"
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :image
          .field-input
            = f.file_field :image
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .field
          .field-label
            = f.label :password
            %i 
          .field-input
            = f.password_field :password, autocomplete: "off"
        -# .field
        -#   .field-label
        -#     = f.label :password_confirmation
        -#   .field-input
        -#     = f.password_field :password_confirmation, autocomplete: "off"
        .actions
          = f.submit "Update", class: 'btn'

app/views/users/follow_list.html.haml
.wrapper
  = render "/posts/header"
  .from
    .from__like
      = @user.name
      さんがフォローした人
      - @user.all_following.each do |user|
        %ul.from__like__user
          %li.from__like__icon
            = image_tag user.image.url, width: '100%',height:'100%', class: "from__icon__link"
          %li.from__like__name
            = link_to user.name, user_path(user), class: "from__name__link"             
  = render "/posts/footer"

app/views/users/follower_list.haml
.wrapper
  = render "/posts/header"
  .from
    .from__like
      = @user.name
      さんをフォローした人
      - @user.followers.each do |user|
        %ul.from__like__user
          %li.from__like__icon
            = image_tag user.image.url, width: '100%',height:'100%', class: "from__icon__link"
          %li.from__like__name
            = link_to user.name, user_path(user), class: "from__name__link"             
  = render "/posts/footer"

app/views/users/show.html.haml
.wrapper
  = render "/posts/header"
  
  .show__user__page
    .show__user__details
      .show__user__details-icon
        = image_tag @user.image.url, width: '100%',height:'100%', class: "details-icon"
      .show__user__details-name
        = @user.name
        さんのページ
      .like-count
        いいねした数 :
        = link_to @user.likes.count, forlike_post_path, class: "like-count-link"
      .follow__content
        .follow__box
          = link_to "フォロー :", {controller: :users,action: :follow_list,user_id: @user.id}, class: "follow__box__link", method: :get
          .follow__box__count
            = @user.follow_count
        .follower__box
          = link_to "フォロワー :", {controller: :users,action: :follower_list,user_id: @user.id}, class: "follower__box__link", method: :get
          .follower__box__count
            = @user.followers_count
        - if current_user.id != @user.id
          = render 'follow_form'


      .show__user__details-like
  %ul.content_search
    - @posts.each do |post|
      %li.search_post
        = link_to post_path(post.id), method: :get, class: "link__group" do
          .post_image
            = image_tag post.image.url, width: '100%',height:'100%'
            -# %img(src="post.image")
          %ul.post_title
            %li
              = post.title
            %li
              -# -if current_user.already_liked?(@post)
              = icon('fas', 'heart', class: "like-icon-off")
              -# -else
              -# = icon('fas', 'heart', class: "like-icon-on")
              = post.liked_users.count
    = paginate(@posts)
  = render "/posts/footer"